apiVersion: v1
kind: Service
metadata:
  name: {{ include "the-artifact.fullname" . }}
  labels:
    {{- include "the-artifact.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "the-artifact.selectorLabels" (list . "app") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
